/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	yogeshdevv1alpha1 "github.com/yogeshthosare/permsync/pkg/apis/yogesh.dev/v1alpha1"
	versioned "github.com/yogeshthosare/permsync/pkg/client/clientset/versioned"
	internalinterfaces "github.com/yogeshthosare/permsync/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/yogeshthosare/permsync/pkg/client/listers/yogesh.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PermsyncInformer provides access to a shared informer and lister for
// Permsyncs.
type PermsyncInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PermsyncLister
}

type permsyncInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPermsyncInformer constructs a new informer for Permsync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPermsyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPermsyncInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPermsyncInformer constructs a new informer for Permsync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPermsyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.YogeshV1alpha1().Permsyncs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.YogeshV1alpha1().Permsyncs(namespace).Watch(context.TODO(), options)
			},
		},
		&yogeshdevv1alpha1.Permsync{},
		resyncPeriod,
		indexers,
	)
}

func (f *permsyncInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPermsyncInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *permsyncInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&yogeshdevv1alpha1.Permsync{}, f.defaultInformer)
}

func (f *permsyncInformer) Lister() v1alpha1.PermsyncLister {
	return v1alpha1.NewPermsyncLister(f.Informer().GetIndexer())
}
