/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/yogeshthosare/permsync/pkg/apis/yogesh.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePermsyncs implements PermsyncInterface
type FakePermsyncs struct {
	Fake *FakeYogeshV1alpha1
	ns   string
}

var permsyncsResource = schema.GroupVersionResource{Group: "yogesh.dev", Version: "v1alpha1", Resource: "permsyncs"}

var permsyncsKind = schema.GroupVersionKind{Group: "yogesh.dev", Version: "v1alpha1", Kind: "Permsync"}

// Get takes name of the permsync, and returns the corresponding permsync object, and an error if there is any.
func (c *FakePermsyncs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Permsync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(permsyncsResource, c.ns, name), &v1alpha1.Permsync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Permsync), err
}

// List takes label and field selectors, and returns the list of Permsyncs that match those selectors.
func (c *FakePermsyncs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PermsyncList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(permsyncsResource, permsyncsKind, c.ns, opts), &v1alpha1.PermsyncList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PermsyncList{ListMeta: obj.(*v1alpha1.PermsyncList).ListMeta}
	for _, item := range obj.(*v1alpha1.PermsyncList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested permsyncs.
func (c *FakePermsyncs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(permsyncsResource, c.ns, opts))

}

// Create takes the representation of a permsync and creates it.  Returns the server's representation of the permsync, and an error, if there is any.
func (c *FakePermsyncs) Create(ctx context.Context, permsync *v1alpha1.Permsync, opts v1.CreateOptions) (result *v1alpha1.Permsync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(permsyncsResource, c.ns, permsync), &v1alpha1.Permsync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Permsync), err
}

// Update takes the representation of a permsync and updates it. Returns the server's representation of the permsync, and an error, if there is any.
func (c *FakePermsyncs) Update(ctx context.Context, permsync *v1alpha1.Permsync, opts v1.UpdateOptions) (result *v1alpha1.Permsync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(permsyncsResource, c.ns, permsync), &v1alpha1.Permsync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Permsync), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePermsyncs) UpdateStatus(ctx context.Context, permsync *v1alpha1.Permsync, opts v1.UpdateOptions) (*v1alpha1.Permsync, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(permsyncsResource, "status", c.ns, permsync), &v1alpha1.Permsync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Permsync), err
}

// Delete takes name of the permsync and deletes it. Returns an error if one occurs.
func (c *FakePermsyncs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(permsyncsResource, c.ns, name), &v1alpha1.Permsync{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePermsyncs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(permsyncsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PermsyncList{})
	return err
}

// Patch applies the patch and returns the patched permsync.
func (c *FakePermsyncs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Permsync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(permsyncsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Permsync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Permsync), err
}
